# Generated by Django 4.2 on 2023-04-19 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bank', 'Bank'), ('Buro', 'Buro')], default='Buro', max_length=20)),
                ('title', models.TextField(blank=True, max_length=100)),
                ('adress', models.TextField(blank=True)),
                ('number_phone', models.BigIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
