# Generated by Django 4.2 on 2023-04-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_remove_organisations_type_alter_organisations_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='type',
            field=models.TextField(choices=[('Bank', 'Bank'), ('Buro', 'Buro')], default='Buro'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
