# Generated by Django 4.2 on 2023-04-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_organisations_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuta', models.CharField(choices=[('Dollar USA', 'USD'), ('Рубль', 'RUB'), ('EURO', 'EURO'), ('Тенге', 'Tenge')], default='USD')),
                ('buy', models.IntegerField(default=0)),
                ('sell', models.IntegerField(default=0)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='currency.organisations')),
            ],
        ),
    ]
