# Generated by Django 4.2 on 2023-04-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='valuta',
            field=models.CharField(choices=[('Dollar USA', 'USD'), ('Рубль', 'RUB'), ('EURO', 'EURO'), ('Тенге', 'Tenge')]),
        ),
    ]
