# Generated by Django 4.2 on 2023-04-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_currency_created_at_alter_currency_valuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
