# Generated by Django 4.2 on 2023-04-20 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0008_alter_currency_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='currency.organisations', verbose_name='Организация')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ragtins', to=settings.AUTH_USER_MODEL, verbose_name='Владелец рейтинга')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='currency.organisations', verbose_name='Организация')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Владелец коммента')),
            ],
        ),
    ]
